export const GET_USER_REQUESTED = 'GET_USER_REQUESTED';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';


export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_FORMS_REQUEST = 'USER_FORMS_REQUEST';
export const USER_FORMS_SUCCESS = 'USER_FORMS_SUCCESS';
export const USER_FORMS_FAIL = 'USER_FORMS_SUCCESS';
