export const GET_USER_REQUESTED = 'GET_USER_REQUESTED';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';


export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGIN_RESTOREAPPKEY = 'USER_LOGIN_RESTOREAPPKEY';

export const USER_FORMS_REQUEST = 'USER_FORMS_REQUEST';
export const USER_FORMS_SUCCESS = 'USER_FORMS_SUCCESS';
export const USER_FORMS_FAIL = 'USER_FORMS_SUCCESS';

export const FORM_SUBMISSION_REQUEST = 'FORM_SUBMISSION_REQUEST';
export const FORM_SUBMISSION_SUCCESS = 'FORM_SUBMISSION_SUCCESS';
export const FORM_SUBMISSION_FAIL = 'FORM_SUBMISSION_FAIL';

export const FORM_QUESTIONS_REQUEST = 'FORM_QUESTIONS_REQUEST';
export const FORM_QUESTIONS_SUCCESS = 'FORM_QUESTIONS_SUCCESS';
export const FORM_QUESTIONS_FAIL = 'FORM_QUESTIONS_FAIL';

