export const GET_USER_REQUESTED = 'GET_USER_REQUESTED';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL';

export const USER_FORMS_REQUEST = 'USER_FORMS_REQUEST';
export const USER_FORMS_SUCCESS = 'USER_FORMS_SUCCESS';
export const USER_FORMS_FAIL = 'USER_FORMS_SUCCESS';

export const FORM_SUBMISSION_REQUEST = 'FORM_SUBMISSION_REQUEST';
export const FORM_SUBMISSION_SUCCESS = 'FORM_SUBMISSION_SUCCESS';
export const FORM_SUBMISSION_FAIL = 'FORM_SUBMISSION_FAIL';

export const FORM_QUESTIONS_REQUEST = 'FORM_QUESTIONS_REQUEST';
export const FORM_QUESTIONS_SUCCESS = 'FORM_QUESTIONS_SUCCESS';
export const FORM_QUESTIONS_FAIL = 'FORM_QUESTIONS_FAIL';

export const FORM_SUBMISSIONPOST_REQUEST = 'FORM_SUBMISSIONPOST_REQUEST';
export const SUBMISSION_SELECT = 'SUBMISSION_SELECT';
